### ISSUE TITLE
Add instructions to README to run your cuke suite

### ISSUE THREAD

**Issue by jasnow** [bbc/wally#12]
Please add developer/tester instructions to README to run your cuke suite.

**Comment by AndrewVos** [comment]
`bundle exec cucumber`?

**Comment by jasnow** [comment]
https://gist.github.com/anonymous/7196095

**Comment by AndrewVos** [comment]
Ok you need to have mongodb installed and running.

http://www.mongodb.org/

**Comment by jasnow** [comment]
Old issue, closing.
