### ISSUE TITLE
"no such file to load" when running `wally server`

### ISSUE THREAD

**Issue by sampart** [bbc/wally#9]
When I run `wally server`, I see the following error:

```
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- bundler/setup (LoadError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/wally-0.0.45/bin/../lib/wally.rb:2
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/wally-0.0.45/bin/wally:5
    from /usr/local/bin/wally:19:in `load'
    from /usr/local/bin/wally:19
```

Any ideas/suggestions?  Thanks

**Version numbers**
- The gem install told me that Wally is wally-0.0.45
- ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
- Ubuntu 12.04.1 LTS

**Comment by coderkind** [comment]
The installation instructions aren't clear enough unfortunately. I'm getting:

/usr/local/lib/ruby/gems/1.9.1/gems/mongo-1.7.0/lib/mongo/connection.rb:440:in `connect': Failed to connect to a master node at localhost:27017 (Mongo::ConnectionFailure)
    from /usr/local/lib/ruby/gems/1.9.1/gems/mongo-1.7.0/lib/mongo/connection.rb:584:in`setup'
    from /usr/local/lib/ruby/gems/1.9.1/gems/mongo-1.7.0/lib/mongo/connection.rb:135:in `initialize'
    from /usr/local/lib/ruby/gems/1.9.1/gems/wally-0.0.45/lib/wally/application.rb:22:in`new'
    from /usr/local/lib/ruby/gems/1.9.1/gems/wally-0.0.45/lib/wally/application.rb:22:in `<top (required)>'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/wally-0.0.45/lib/wally.rb:7:in`<top (required)>'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /usr/local/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /usr/local/lib/ruby/gems/1.9.1/gems/wally-0.0.45/bin/wally:5:in `<top (required)>'
    from /usr/local/bin/wally:19:in`load'
    from /usr/local/bin/wally:19:in `<main>'

...but I appreciate there are previous steps in the instructions that haven't been straightforward either (internal proxy problems, etc).

**Comment by MikePearce** [comment]
I found it was because I was running ruby 2.0.0p0, which isn't compatible with bundler 1.2.3, so I ran 

```
gem install bundler --pre
```

and it all worked. See here: https://github.com/carlhuda/bundler/issues/2204

**Comment by sampart** [comment]
That solves my problem; thanks!  I did have another issue down the line, but I may raise a separate issue for that if I can't get it resolved, so I'll close this issue.
